#%RAML 1.0 Trait


responses:
  200:
    body:
      application/json:
        type: object
        properties:
          sequence-of-flow: 
            type: string
            description: return sequence of flow which is executed