name: Add to Exchange and Deploy to Sandbox

on:
  push:
    branches:
      - dev

env:
  APPID: ${{ secrets.mule_connected_app_sand_id }}
  APPSECRET: ${{ secrets.mule_connected_app_sand_secret }}

jobs:
  exchangedep:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./mcd2-impl
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        repositories: '[{ "id": "anypoint-exchange-v3", "url": "https://maven.anypoint.mulesoft.com/api/v3/maven" }]'
        servers: '[{ "id": "anypoint-exchange-v3", "username": "~~~Client~~~", "password": "${env.APPID}~?~${env.APPSECRET}" }]'
    - name: Package jar
      run: |
        mvn clean package
    - name: Upload artifact 
      uses: actions/upload-artifact@master
      with:
        name: artifacts
        path: target/*.jar      
    - name: Deploy to Exchange
      run: |
        artifactName=$(ls *.jar | head -1)
        mvn clean mule:deploy \
         -Dmule.artifact=$artifactName

  deploy:
    needs: exchangedep
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./mcd2-impl
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3
    - uses: actions/download-artifact@master
      with:
        name: artifacts
    - name: Deploy to Sandbox
      run: |
        artifactName=$(ls *.jar | head -1)
        mvn clean mule:deploy -DmuleDeploy \
         -Dmule.artifact=$artifactName \
         -Denvironment="Sandbox" \
         -Dtarget.env="dev" \
         -Danypoint.psname="Cloudhub-US-East-2"  \
         -Dconnected.app.id="$APPID" \
         -Dconnected.app.secret="$APPSECRET"